inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/bundle/**/*
    - db/migrate/**/*
    - bin/*
    - db/**/*
    - config/**/*
    - Gemfile
Rails:
  Enabled: true

AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Max: 50
